// <auto-generated />
using System;
using HospitalVeterinario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalVeterinario.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502030316_AgregarMesAnioNomina")]
    partial class AgregarMesAnioNomina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asistio")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreDepartamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("BonificacionDecreto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DPI")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoEmpleado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasUser")
                        .HasColumnType("bit");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<string>("NIT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreBanco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCuentaBancaria")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroIGSS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoContrato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCuentaBancaria")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdPuesto");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoAusencias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DescuentoIGSS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DescuentoISR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DescuentoSeptimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiasAusentes")
                        .HasColumnType("int");

                    b.Property<int>("DiasHabilesMes")
                        .HasColumnType("int");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NivelProductividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeProductividad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioPagado")
                        .HasColumnType("int");

                    b.Property<decimal?>("BonificacionDecreto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BonoEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DescuentoIGSS")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("DescuentoISR")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("DiasLaborados")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsIndemnizacion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasExtras")
                        .HasColumnType("int");

                    b.Property<decimal?>("Indemnizacion")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MesPagado")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoBruto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoNeto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PagoHorasExtras")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Quincena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPago")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("DescripcionPuesto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("NivelJerarquico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePuesto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdPuesto");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Vacacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SalioDeVacaciones")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Vacacion");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Asistencia", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Empleado", "Empleado")
                        .WithMany("Asistencias")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Empleado", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Puesto", "IdPuestoNavigation")
                        .WithMany()
                        .HasForeignKey("IdPuesto");

                    b.Navigation("IdPuestoNavigation");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Nomina", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Pago", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.User", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Vacacion", b =>
                {
                    b.HasOne("HospitalVeterinario.Data.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HospitalVeterinario.Data.Models.Empleado", b =>
                {
                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
